/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    media: Media;
    'lfrs-likes': LfrsLike;
    'lfrs-dislikes': LfrsDislike;
    'lfrs-favourites': LfrsFavourite;
    'lfrs-reviews': LfrsReview;
    'lfrs-replies': LfrsReply;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'lfrs-reviews': {
      replies: 'lfrs-replies';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'lfrs-likes': LfrsLikesSelect<false> | LfrsLikesSelect<true>;
    'lfrs-dislikes': LfrsDislikesSelect<false> | LfrsDislikesSelect<true>;
    'lfrs-favourites': LfrsFavouritesSelect<false> | LfrsFavouritesSelect<true>;
    'lfrs-reviews': LfrsReviewsSelect<false> | LfrsReviewsSelect<true>;
    'lfrs-replies': LfrsRepliesSelect<false> | LfrsRepliesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'lfrs-settings': LfrsSetting;
  };
  globalsSelect: {
    'lfrs-settings': LfrsSettingsSelect<false> | LfrsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles?: ('admin' | 'subscriber')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content?: string | null;
  author?: (string | null) | User;
  publishedDate?: string | null;
  lfrs?: {
    likesCount?: number | null;
    dislikesCount?: number | null;
    favouritesCount?: number | null;
    ratingsCount?: number | null;
    ratingsAverage?: number | null;
    reviewsCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-likes".
 */
export interface LfrsLike {
  id: string;
  user: string | User;
  targetCollection: string;
  targetDoc: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-dislikes".
 */
export interface LfrsDislike {
  id: string;
  user: string | User;
  targetCollection: string;
  targetDoc: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-favourites".
 */
export interface LfrsFavourite {
  id: string;
  user: string | User;
  targetCollection: string;
  targetDoc: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-reviews".
 */
export interface LfrsReview {
  id: string;
  user: string | User;
  targetCollection: string;
  targetDoc: string;
  title?: string | null;
  body?: string | null;
  score?: number | null;
  media?:
    | {
        file: string | Media;
        id?: string | null;
      }[]
    | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  repliesCount?: number | null;
  replies?: {
    docs?: (string | LfrsReply)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  lfrs?: {
    likesCount?: number | null;
    dislikesCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-replies".
 */
export interface LfrsReply {
  id: string;
  user: string | User;
  review: string | LfrsReview;
  body: string;
  status?: ('pending' | 'approved' | 'rejected') | null;
  lfrs?: {
    likesCount?: number | null;
    dislikesCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'lfrs-likes';
        value: string | LfrsLike;
      } | null)
    | ({
        relationTo: 'lfrs-dislikes';
        value: string | LfrsDislike;
      } | null)
    | ({
        relationTo: 'lfrs-favourites';
        value: string | LfrsFavourite;
      } | null)
    | ({
        relationTo: 'lfrs-reviews';
        value: string | LfrsReview;
      } | null)
    | ({
        relationTo: 'lfrs-replies';
        value: string | LfrsReply;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  publishedDate?: T;
  lfrs?:
    | T
    | {
        likesCount?: T;
        dislikesCount?: T;
        favouritesCount?: T;
        ratingsCount?: T;
        ratingsAverage?: T;
        reviewsCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-likes_select".
 */
export interface LfrsLikesSelect<T extends boolean = true> {
  user?: T;
  targetCollection?: T;
  targetDoc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-dislikes_select".
 */
export interface LfrsDislikesSelect<T extends boolean = true> {
  user?: T;
  targetCollection?: T;
  targetDoc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-favourites_select".
 */
export interface LfrsFavouritesSelect<T extends boolean = true> {
  user?: T;
  targetCollection?: T;
  targetDoc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-reviews_select".
 */
export interface LfrsReviewsSelect<T extends boolean = true> {
  user?: T;
  targetCollection?: T;
  targetDoc?: T;
  title?: T;
  body?: T;
  score?: T;
  media?:
    | T
    | {
        file?: T;
        id?: T;
      };
  status?: T;
  repliesCount?: T;
  replies?: T;
  lfrs?:
    | T
    | {
        likesCount?: T;
        dislikesCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-replies_select".
 */
export interface LfrsRepliesSelect<T extends boolean = true> {
  user?: T;
  review?: T;
  body?: T;
  status?: T;
  lfrs?:
    | T
    | {
        likesCount?: T;
        dislikesCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-settings".
 */
export interface LfrsSetting {
  id: string;
  reviewModeration?: boolean | null;
  enableReviewMedia?: boolean | null;
  enableReviewReactions?: boolean | null;
  /**
   * Manage active LFRs features for the posts collection.
   */
  posts?: {
    likes?: boolean | null;
    dislikes?: boolean | null;
    favourites?: boolean | null;
    ratings?: boolean | null;
    reviews?: boolean | null;
    replies?: boolean | null;
    allowMultipleReviews?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lfrs-settings_select".
 */
export interface LfrsSettingsSelect<T extends boolean = true> {
  reviewModeration?: T;
  enableReviewMedia?: T;
  enableReviewReactions?: T;
  posts?:
    | T
    | {
        likes?: T;
        dislikes?: T;
        favourites?: T;
        ratings?: T;
        reviews?: T;
        replies?: T;
        allowMultipleReviews?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}